DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
Paginate = 10
SectionPagesMenu = "main"
baseURL = "https://distracted-hopper-50f30d.netlify.com"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
theme = "ananke"
title = "Enable Busoga"
[params]
background_color_class = "bg-black"
description = "Helping others help themselves by transfering expertise, equipment and finance."
facebook = ""
favicon = "favicon.ico"
featured_image = "/images/enable.jpg"
footer = "Registered Charity No. 1157485"
github = ""
instagram = ""
linkedin = ""
recent_posts_number = 3
twitter = ""
youtube = "https://www.youtube.com/results?search_query=enable+busoga"
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
