title = "Enable Busoga"
baseURL = "distracted-hopper-50f30d.netlify.com"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Helping others help themselves by transfering expertise, equipment and finance."
  facebook = ""
  twitter = "https://twitter.com/RichardTrimble7"
  instagram = ""
  youtube = "https://www.youtube.com/channel/UCLnGGRG__uGSPLBLzyhg8dQ"
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/enable.jpg"
  recent_posts_number = 3
  footer = "Registered Charity No. 1157485"
