---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: content/programmes
  label: Programmes
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/news
  label: News
  create: all
  match: "**/*"
- type: directory
  path: data
  label: Data
  create: none
  match: "**/*.{json,yaml,yml,toml}"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.44'
