---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- path: content/programmes
  label: Programmes
  create: all
- path: content
  label: Pages
  create: all
- path: content/news
  label: News
  create: all
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.44'
